name: Update README with Weather

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install curl and jq
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Run update script
      run: |
        bash scripts/update_readme.sh
      env:
        IMAGES: <p align="center"><a href="https://github.com/${{ github.repository }}/graphs/contributors"><img align="center" src="https://img.shields.io/github/contributors/${{ github.repository }}"></a> <a href="https://github.com/${{ github.repository }}/issues"><img align="center" src="https://img.shields.io/github/issues/${{ github.repository }}"></a> <a href="https://github.com/${{ github.repository }}/pulls"><img align="center" src="https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=shields"></a> <a href="https://github.com/${{ github.repository }}/pulls"><img align="center" src="https://img.shields.io/github/issues-pr/${{ github.repository }}"></a> <a href="https://github.com/${{ github.repository }}/commits/main/"><img align="center" src="https://img.shields.io/github/commit-activity/m/${{ github.repository }}"></a> <img align="center" src="https://github.com/Julius-Ulee/github-profile-views-counter/blob/master/svg/736731255/badge.svg"> <img height='20' align="center" src="https://github.com/Julius-Ulee/github-profile-views-counter/blob/master/graph/736731255/small/week.png"><br><a href="https://github.com/${{ github.repository }}"><img align="center" src="https://img.shields.io/maintenance/yes/2024"></a></p>
        BADGES: <p align="center"><b>Display GitHub Action Badge</b> <a href="https://github.com/${{ github.repository }}/actions/workflows/weather.yml"><img align="center" src="https://github.com/${{ github.repository }}/actions/workflows/weather.yml/badge.svg"></a></p>
        INFO: <p align="center"><a href="https://github.com/${{ github.repository }}/blob/main/README.md">Readme</a> • <a href="https://github.com/${{ github.repository }}/blob/main/.github/workflows/weather.yml">Weather-YML</a> • <a href="https://github.com/${{ github.repository }}/blob/main/LICENSE">License</a> • <a href="https://github.com/${{ github.repository }}/blob/main/scripts/update_readme.sh">update-readme</a> • <a href="https://github.com/${{ github.repository }}/blob/main/weather.json">Weather Data</a></p>
        POWERED: <li>Powered by <a href="https://github.com/Julius-Ulee/Daily-Weather-Report">Daily-Weather-Report</a></li>
        LICENSE: <li><a href="https://github.com/${{ github.repository }}/blob/main/LICENSE"><img src="https://img.shields.io/badge/License-MIT-yellow.svg"></a></li>
        OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
